version: 2
formats: []

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
