# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.mixins import EqualityComparable, Hashable

__all__ = ("EqualityComparable", "Hashable")
