# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.reaction import (
    TYPE_CHECKING,
    Any,
    Optional,
    Reaction,
    ReactionIterator,
    Union,
    annotations,
)

__all__ = "Reaction"
