# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.ext.commands.context import (
    MISSING,
    TYPE_CHECKING,
    Any,
    BotT,
    CogT,
    Context,
    Dict,
    Generic,
    List,
    Message,
    Optional,
    P,
    T,
    TypeVar,
    Union,
    annotations,
    inspect,
    nextcord,
    re,
)

__all__ = "Context"
