# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.ext.commands.help import (
    TYPE_CHECKING,
    Command,
    CommandError,
    DefaultHelpCommand,
    Group,
    HelpCommand,
    MinimalHelpCommand,
    Optional,
    Paginator,
    _HelpCommandImpl,
    _not_overriden,
    copy,
    functools,
    inspect,
    itertools,
    nextcord,
    re,
)

__all__ = ("Paginator", "HelpCommand", "DefaultHelpCommand", "MinimalHelpCommand")
