# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.types.member import (
    Member,
    MemberWithUser,
    Nickname,
    PartialMember,
    SnowflakeList,
    TypedDict,
    User,
    UserWithMember,
    _OptionalMemberWithUser,
)
