# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.types.sticker import (
    BaseSticker,
    CreateGuildSticker,
    EditGuildSticker,
    GuildSticker,
    List,
    ListPremiumStickerPacks,
    Literal,
    Snowflake,
    StandardSticker,
    Sticker,
    StickerFormatType,
    StickerItem,
    StickerPack,
    TypedDict,
    Union,
    User,
    _CreateGuildStickerOptional,
    _GuildStickerOptional,
    annotations,
)
