# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.types.template import (
    CreateTemplate,
    Guild,
    Optional,
    Snowflake,
    Template,
    TypedDict,
    User,
    annotations,
)
