# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.types.user import (
    Literal,
    Optional,
    PartialUser,
    PremiumType,
    Snowflake,
    TypedDict,
    User,
)
