# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""

from nextcord.types.webhook import (
    FollowerWebhook,
    Literal,
    Optional,
    PartialChannel,
    PartialWebhook,
    Snowflake,
    SourceGuild,
    TypedDict,
    User,
    Webhook,
    WebhookType,
    _FollowerWebhookOptional,
    _FullWebhook,
    _WebhookOptional,
    annotations,
)
